server:
  port: 18100

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/admin/auth/**,/admin/user/**,/admin/role/**,/admin/permission/**,/blog/auth/**
          filters:
            - StripPrefix=1

        - id: content
          uri: lb://content
          predicates:
            - Path=/admin/article/**,/admin/category/**,/admin/tag/**,/blog/article/**,/blog/category/**,/blog/tag/**,/blog/archive/**
          filters:
            - StripPrefix=1

        - id: interaction
          uri: lb://interaction
          predicates:
            - Path=/admin/comment/**,/admin/message/**,/blog/comment/**,/blog/like/**,/blog/favorite/**,/blog/message/**
          filters:
            - StripPrefix=1

        - id: file
          uri: lb://file
          predicates:
            - Path=/admin/file/**,/blog/file/**
          filters:
            - StripPrefix=1

very:
  gateway:
    auth:
      white-list:
        - /admin/auth/login
        - /blog/**
        - /favicon.ico

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
