spring:
  data:
    redis:
      host: 127.0.0.1
      port: 36379
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 3000ms
